cache:
  - name: tfg-dev-redis
    host: http://143.244.206.126
    port: 6384
  - name: tfg-preprod-redis
    host: http://143.244.206.126
    port: 6385
  - name: tfg-prod-redis
    host: http://143.244.206.126
    port: 6386

devMinor:
  workflowId: main-dev-update-poetry-version.yaml
  workflowRepository: carlosruperez/go-fleet-manager

maintenanceMode:
  workflowId: main-maintenance.yaml
  workflowRepository: carlosruperez/go-fleet-manager

prodDeployment:
  workflowId: main-deployment.yaml
  workflowRepository: carlosruperez/go-fleet-manager

createMainPR:
  workflowId: main-pr-release-to-main.yaml
  workflowRepository: carlosruperez/go-fleet-manager
environments:
  development: "http://143.244.206.126:8000/dev/"
  staging: "http://143.244.206.126:8000/pre/"
  production: "http://143.244.206.126:8000/prod/"
