name: Gofmt

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.3'

    - name: Run gofmt and check for changes
      run: |
        gofmt -s -w .
        git add .
        if git diff --cached --quiet; then
          echo "No changes from gofmt"
        else
          echo "Changes detected from gofmt"
          git config --global user.email "carlosruperez.h@gmail.com"
          git config --global user.name "carlosruperez"
          git commit -m "[skip ci] Auto-format Go code with gofmt"
          git push origin HEAD:refs/heads/${{ github.head_ref }}
        fi
