name: Create PR from ${{ inputs.releaseBranch }} to main
run-name: PR from ${{ inputs.appGithubRepository }}  ${{ inputs.releaseBranch }} to main

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'Release branch name to do the PR'
        required: true
        type: string
      appGithubRepository:
        description: 'Application Github Repository'
        required: true
        type: choice
        options:
        - 'carlosruperez/tfg-ms-foo1-api-server'
        - 'carlosruperez/tfg-ms-foo2-api-server'

jobs:
  poetry_version:
    name: Create PR to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.appGithubRepository }} # Ex: celering/travels-ms-configuration-daas-api-server
          token: ${{ secrets.AUTOMATION_GITHUB_API_TOKEN }}
          ref: ${{ github.event.inputs.releaseBranch }}
      - name: PR to main
        env:
          GH_TOKEN: ${{ secrets.AUTOMATION_GITHUB_API_TOKEN }}
        id: pr_create
        run: |
          gh pr create --base main --head ${{ github.event.inputs.releaseBranch }} --title "from ${{ github.event.inputs.releaseBranch }} to main" --body ""
